# 🐼 Pandas — From Basic to Advanced

A comprehensive guide covering **Series**, **DataFrames**, **indexing**, **data cleaning**, **merging**, **groupby**, **time series**, **performance**, and more.

In [1]:
import pandas as pd
import numpy as np

print(f'pandas version: {pd.__version__}')
print(f'numpy  version: {np.__version__}')

pandas version: 3.0.5
numpy  version: 2.4.6

---
## 🟢 Level 1 — Basics

### 1.1 Series

In [2]:
# From list
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'], name='scores')
print(s)
print('dtype :', s.dtype)
print('index :', s.index.tolist())
print('values:', s.values)

a    10
b    20
c    30
Name: scores, dtype: int64
dtype : int64
index : ['a', 'b', 'c']
values: [10 20 30]

In [3]:
# From dict
s2 = pd.Series({'python': 90, 'sql': 85, 'ml': 92})
print(s2)
print('Max skill:', s2.idxmax(), '→', s2.max())

python    90
sql       85
ml        92
dtype: int64
Max skill: ml → 92

### 1.2 DataFrame Creation

In [4]:
data = {
    'name' : ['Alice', 'Bob', 'Carol', 'Dave', 'Eve'],
    'dept' : ['Eng', 'DS', 'Eng', 'DS', 'PM'],
    'salary': [90000, 85000, 95000, 88000, 78000],
    'yoe'  : [5, 3, 7, 4, 2],
    'remote': [True, False, True, True, False],
}

df = pd.DataFrame(data)
df

    name dept  salary  yoe  remote
0  Alice  Eng   90000    5    True
1    Bob   DS   85000    3   False
2  Carol  Eng   95000    7    True
3   Dave   DS   88000    4    True
4    Eve   PM   78000    2   False

In [5]:
# Basic info
print(df.shape)      # (rows, cols)
print(df.dtypes)
df.info()

(5, 5)
name        str
dept        str
salary    int64
yoe       int64
remote     bool
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   dept    5 non-null      str
 2   salary  5 non-null      int64
 3   yoe     5 non-null      int64
 4   remote  5 non-null      bool
dtypes: bool(1), int64(2), str(2)
memory usage: 297.0 bytes

In [6]:
df.describe()

             salary       yoe
count      5.000000  5.000000
mean   87200.000000  4.200000
std     6300.793601  1.923538
min    78000.000000  2.000000
25%    85000.000000  3.000000
50%    88000.000000  4.000000
75%    90000.000000  5.000000
max    95000.000000  7.000000

### 1.3 Selecting Columns & Rows

In [7]:
# Single column → Series
print(df['name'])

# Multiple columns → DataFrame
df[['name', 'salary']]

0    Alice
1      Bob
2    Carol
3     Dave
4      Eve
Name: name, dtype: str

    name  salary
0  Alice   90000
1    Bob   85000
2  Carol   95000
3   Dave   88000
4    Eve   78000

In [8]:
# loc  — label-based
print(df.loc[0])          # row 0
print(df.loc[1:3, 'name':'salary'])  # slice rows & cols

name      Alice
dept        Eng
salary    90000
yoe           5
remote     True
Name: 0, dtype: object
    name dept  salary
1    Bob   DS   85000
2  Carol  Eng   95000
3   Dave   DS   88000

In [9]:
# iloc — position-based
print(df.iloc[0])         # first row
print(df.iloc[:, :3])     # all rows, first 3 cols

name      Alice
dept        Eng
salary    90000
yoe           5
remote     True
Name: 0, dtype: object
    name dept  salary
0  Alice  Eng   90000
1    Bob   DS   85000
2  Carol  Eng   95000
3   Dave   DS   88000
4    Eve   PM   78000

### 1.4 Basic Filtering

In [10]:
# Boolean mask
df[df['salary'] > 88000]

    name dept  salary  yoe  remote
0  Alice  Eng   90000    5    True
2  Carol  Eng   95000    7    True

In [11]:
# Multiple conditions
df[(df['dept'] == 'Eng') & (df['yoe'] >= 5)]

    name dept  salary  yoe  remote
0  Alice  Eng   90000    5    True
2  Carol  Eng   95000    7    True

In [12]:
# query() — SQL-like syntax
df.query("dept == 'DS' and salary > 85000")

   name dept  salary  yoe  remote
3  Dave   DS   88000    4    True

### 1.5 Adding & Modifying Columns

In [13]:
df['salary_lpa'] = df['salary'] / 1000          # new column
df['senior']     = df['yoe'] >= 5               # boolean column
df['level']      = df['yoe'].apply(lambda y: 'Senior' if y >= 5 else 'Junior')
df

    name dept  salary  yoe  remote  salary_lpa  senior   level
0  Alice  Eng   90000    5    True        90.0    True  Senior
1    Bob   DS   85000    3   False        85.0   False  Junior
2  Carol  Eng   95000    7    True        95.0    True  Senior
3   Dave   DS   88000    4    True        88.0   False  Junior
4    Eve   PM   78000    2   False        78.0   False  Junior

---
## 🟡 Level 2 — Intermediate

### 2.1 Sorting

In [14]:
df.sort_values('salary', ascending=False)

    name dept  salary  yoe  remote  salary_lpa  senior   level
2  Carol  Eng   95000    7    True        95.0    True  Senior
0  Alice  Eng   90000    5    True        90.0    True  Senior
3   Dave   DS   88000    4    True        88.0   False  Junior
1    Bob   DS   85000    3   False        85.0   False  Junior
4    Eve   PM   78000    2   False        78.0   False  Junior

In [15]:
# Sort by multiple keys
df.sort_values(['dept', 'salary'], ascending=[True, False])

    name dept  salary  yoe  remote  salary_lpa  senior   level
3   Dave   DS   88000    4    True        88.0   False  Junior
1    Bob   DS   85000    3   False        85.0   False  Junior
2  Carol  Eng   95000    7    True        95.0    True  Senior
0  Alice  Eng   90000    5    True        90.0    True  Senior
4    Eve   PM   78000    2   False        78.0   False  Junior

### 2.2 GroupBy & Aggregation

In [22]:
# iterate over group
grouped = df.groupby('dept')
for group in grouped:
    print(group)
    print("-"*20)

('DS',    name dept  salary  yoe  remote  salary_lpa  senior   level
1   Bob   DS   85000    3   False        85.0   False  Junior
3  Dave   DS   88000    4    True        88.0   False  Junior)
--------------------
('Eng',     name dept  salary  yoe  remote  salary_lpa  senior   level
0  Alice  Eng   90000    5    True        90.0    True  Senior
2  Carol  Eng   95000    7    True        95.0    True  Senior)
--------------------
('PM',   name dept  salary  yoe  remote  salary_lpa  senior   level
4  Eve   PM   78000    2   False        78.0   False  Junior)
--------------------

dept
DS     86500.0
Eng    92500.0
PM     78000.0
Name: salary, dtype: float64

In [24]:
# Mean salary per department
df.groupby('dept')['salary'].mean()

dept
DS     86500.0
Eng    92500.0
PM     78000.0
Name: salary, dtype: float64

In [23]:
# Multiple aggregations
df.groupby('dept').agg(
    avg_salary=('salary', 'mean'),
    max_salary=('salary', 'max'),
    headcount =('name', 'count'),
    avg_yoe   =('yoe', 'mean'),
).round(2)

      avg_salary  max_salary  headcount  avg_yoe
dept
DS       86500.0       88000          2      3.5
Eng      92500.0       95000          2      6.0
PM       78000.0       78000          1      2.0

In [25]:
# Group + filter (having equivalent)
dept_stats = df.groupby('dept')['salary'].mean()
dept_stats[dept_stats > 87000]

dept
Eng    92500.0
Name: salary, dtype: float64

### 2.3 Missing Data

In [26]:
# Introduce NaNs for demo
df_nan = df.copy()
df_nan.loc[1, 'salary'] = np.nan
df_nan.loc[3, 'dept']   = np.nan

print('NaN count per column:')
print(df_nan.isnull().sum())
print('\nAny NaN row:')
df_nan[df_nan.isnull().any(axis=1)]

NaN count per column:
name          0
dept          1
salary        1
yoe           0
remote        0
salary_lpa    0
senior        0
level         0
dtype: int64

Any NaN row:

   name dept   salary  yoe  remote  salary_lpa  senior   level
1   Bob   DS      NaN    3   False        85.0   False  Junior
3  Dave  NaN  88000.0    4    True        88.0   False  Junior

In [27]:
# Fill strategies
df_filled = df_nan.copy()
df_filled['salary'] = df_filled['salary'].fillna(df_filled['salary'].median())
df_filled['dept']   = df_filled['dept'].fillna('Unknown')
df_filled

    name     dept   salary  yoe  remote  salary_lpa  senior   level
0  Alice      Eng  90000.0    5    True        90.0    True  Senior
1    Bob       DS  89000.0    3   False        85.0   False  Junior
2  Carol      Eng  95000.0    7    True        95.0    True  Senior
3   Dave  Unknown  88000.0    4    True        88.0   False  Junior
4    Eve       PM  78000.0    2   False        78.0   False  Junior

In [28]:
# Forward / backward fill (useful for time series)
ts = pd.Series([1, np.nan, np.nan, 4, np.nan])
print('ffill:', ts.ffill().tolist())
print('bfill:', ts.bfill().tolist())

# Drop rows where salary is NaN
df_nan.dropna(subset=['salary'])

ffill: [1.0, 1.0, 1.0, 4.0, 4.0]
bfill: [1.0, 4.0, 4.0, 4.0, nan]

    name dept   salary  yoe  remote  salary_lpa  senior   level
0  Alice  Eng  90000.0    5    True        90.0    True  Senior
2  Carol  Eng  95000.0    7    True        95.0    True  Senior
3   Dave  NaN  88000.0    4    True        88.0   False  Junior
4    Eve   PM  78000.0    2   False        78.0   False  Junior

### 2.4 Merging & Joining

In [29]:
projects = pd.DataFrame({
    'name'   : ['Alice', 'Bob', 'Carol', 'Frank'],
    'project': ['Search', 'Recommend', 'Search', 'Ads'],
})

# inner join (default)
inner = df.merge(projects, on='name')
print('INNER:\n', inner[['name','dept','project']])

# left join
left = df.merge(projects, on='name', how='left')
print('\nLEFT:\n', left[['name','dept','project']])

INNER:
     name dept    project
0  Alice  Eng     Search
1    Bob   DS  Recommend
2  Carol  Eng     Search

LEFT:
     name dept    project
0  Alice  Eng     Search
1    Bob   DS  Recommend
2  Carol  Eng     Search
3   Dave   DS        NaN
4    Eve   PM        NaN

In [32]:
# concat — stack DataFrames
df_new = pd.DataFrame({'name':['Frank'],'dept':['PM'],'salary':[72000],'yoe':[1],'remote':[True]})
df_all = pd.concat([df[['name','dept','salary','yoe','remote']], df_new], ignore_index=True)
df_all

    name dept  salary  yoe  remote
0  Alice  Eng   90000    5    True
1    Bob   DS   85000    3   False
2  Carol  Eng   95000    7    True
3   Dave   DS   88000    4    True
4    Eve   PM   78000    2   False
5  Frank   PM   72000    1    True

### 2.5 String Operations

In [37]:
s = pd.Series(['Alice Smith', 'bob jones', '  Carol White  ', 'DAVE BROWN'])

print(s.str.lower())
print("-"*20)
print(s.str.upper())
print("-"*20)
print(s.str.strip())
print("-"*20)
print(s.str.title())
print("-"*20)
print(s.str.contains('alice', case=False))
print("-"*20)
print(s.str.split(' ').str[0])     # first name
print("-"*20)
print(s.str.replace(r'\s+', '_', regex=True))

0        alice smith
1          bob jones
2      carol white
3         dave brown
dtype: str
--------------------
0        ALICE SMITH
1          BOB JONES
2      CAROL WHITE
3         DAVE BROWN
dtype: str
--------------------
0    Alice Smith
1      bob jones
2    Carol White
3     DAVE BROWN
dtype: str
--------------------
0        Alice Smith
1          Bob Jones
2      Carol White
3         Dave Brown
dtype: str
--------------------
0     True
1    False
2    False
3    False
dtype: bool
--------------------
0    Alice
1      bob
2
3     DAVE
dtype: object
--------------------
0      Alice_Smith
1        bob_jones
2    _Carol_White_
3       DAVE_BROWN
dtype: str

### 2.6 apply / map / transform

In [39]:
# apply on Series
df['salary_band'] = df['salary'].apply(lambda x: 'High' if x > 90000 else ('Mid' if x > 82000 else 'Low'))
print(df[['name','salary','salary_band']])
print("-"*20)
# map — element-wise (replace values)
dept_map = {'Eng': 'Engineering', 'DS': 'Data Science', 'PM': 'Product'}
df['dept_full'] = df['dept'].map(dept_map)
print(df[['dept','dept_full']])

    name  salary salary_band
0  Alice   90000         Mid
1    Bob   85000         Mid
2  Carol   95000        High
3   Dave   88000         Mid
4    Eve   78000         Low
--------------------
  dept     dept_full
0  Eng   Engineering
1   DS  Data Science
2  Eng   Engineering
3   DS  Data Science
4   PM       Product

In [40]:
# transform — keeps original index shape (useful with groupby)
df['dept_avg_salary'] = df.groupby('dept')['salary'].transform('mean')
df['salary_vs_avg']   = df['salary'] - df['dept_avg_salary']
df[['name','dept','salary','dept_avg_salary','salary_vs_avg']]

    name dept  salary  dept_avg_salary  salary_vs_avg
0  Alice  Eng   90000          92500.0        -2500.0
1    Bob   DS   85000          86500.0        -1500.0
2  Carol  Eng   95000          92500.0         2500.0
3   Dave   DS   88000          86500.0         1500.0
4    Eve   PM   78000          78000.0            0.0

---
## 🔴 Level 3 — Advanced

### 3.1 Pivot Tables & Cross-tabs

In [41]:
pivot = df.pivot_table(
    values='salary',
    index='dept',
    columns='remote',
    aggfunc='mean',
    margins=True,         # adds row/col totals
    fill_value=0,
)
pivot

remote    False     True      All
dept
DS      85000.0  88000.0  86500.0
Eng         0.0  92500.0  92500.0
PM      78000.0      0.0  78000.0
All     81500.0  91000.0  87200.0

In [42]:
# Cross-tab: frequency table
pd.crosstab(df['dept'], df['remote'], margins=True)

remote  False  True  All
dept
DS          1     1    2
Eng         0     2    2
PM          1     0    1
All         2     3    5

### 3.2 Multi-level (Hierarchical) Index

In [48]:
multi = df.set_index(['dept', 'name'])[['salary', 'yoe']]
print(multi)
print("-"*20)
print('\nDS department:')
print(multi.loc['DS'])
print("-"*20)
print('\nAlice:')
print(multi.loc[('Eng', 'Alice')])

            salary  yoe
dept name
Eng  Alice   90000    5
DS   Bob     85000    3
Eng  Carol   95000    7
DS   Dave    88000    4
PM   Eve     78000    2
--------------------

DS department:
      salary  yoe
name
Bob    85000    3
Dave   88000    4
--------------------

Alice:
salary    90000
yoe           5
Name: (Eng, Alice), dtype: int64

In [49]:
# Reset index to flatten
multi.reset_index()

  dept   name  salary  yoe
0  Eng  Alice   90000    5
1   DS    Bob   85000    3
2  Eng  Carol   95000    7
3   DS   Dave   88000    4
4   PM    Eve   78000    2

### 3.3 Time Series

In [50]:
# Create a date-indexed series
dates = pd.date_range('2024-01-01', periods=12, freq='ME')  # month-end
revenue = pd.Series(
    np.random.randint(100_000, 500_000, size=12),
    index=dates,
    name='revenue'
)
revenue

2024-01-31    344914
2024-02-29    289909
2024-03-31    131822
2024-04-30    176528
2024-05-31    393469
2024-06-30    142679
2024-07-31    381715
2024-08-31    268565
2024-09-30    173143
2024-10-31    195785
2024-11-30    330599
2024-12-31    187495
Freq: ME, Name: revenue, dtype: int64

In [51]:
# Resample to quarterly sum
print('Quarterly revenue:')
print(revenue.resample('QE').sum())

# Rolling 3-month average
print('\n3-month rolling avg:')
print(revenue.rolling(3).mean().round(0))

Quarterly revenue:
2024-03-31    766645
2024-06-30    712676
2024-09-30    823423
2024-12-31    713879
Freq: QE-DEC, Name: revenue, dtype: int64

3-month rolling avg:
2024-01-31         NaN
2024-02-29         NaN
2024-03-31    255548.0
2024-04-30    199420.0
2024-05-31    233940.0
2024-06-30    237559.0
2024-07-31    305954.0
2024-08-31    264320.0
2024-09-30    274474.0
2024-10-31    212498.0
2024-11-30    233176.0
2024-12-31    237960.0
Freq: ME, Name: revenue, dtype: float64

In [52]:
# Date component extraction
ts_df = pd.DataFrame({'date': pd.date_range('2024-01-01', periods=6, freq='D'), 'value': range(6)})
ts_df['year']    = ts_df['date'].dt.year
ts_df['month']   = ts_df['date'].dt.month
ts_df['weekday'] = ts_df['date'].dt.day_name()
ts_df

        date  value  year  month    weekday
0 2024-01-01      0  2024      1     Monday
1 2024-01-02      1  2024      1    Tuesday
2 2024-01-03      2  2024      1  Wednesday
3 2024-01-04      3  2024      1   Thursday
4 2024-01-05      4  2024      1     Friday
5 2024-01-06      5  2024      1   Saturday

### 3.4 Window Functions

In [53]:
# Rank within group (like SQL RANK OVER PARTITION BY)
df['rank_in_dept'] = df.groupby('dept')['salary'].rank(ascending=False, method='dense').astype(int)
df[['name','dept','salary','rank_in_dept']].sort_values(['dept','rank_in_dept'])

    name dept  salary  rank_in_dept
3   Dave   DS   88000             1
1    Bob   DS   85000             2
2  Carol  Eng   95000             1
0  Alice  Eng   90000             2
4    Eve   PM   78000             1

In [54]:
# Cumulative sum
df_sorted = df.sort_values('salary', ascending=False).reset_index(drop=True)
df_sorted['cumsum_salary'] = df_sorted['salary'].cumsum()
df_sorted[['name','salary','cumsum_salary']]

    name  salary  cumsum_salary
0  Carol   95000          95000
1  Alice   90000         185000
2   Dave   88000         273000
3    Bob   85000         358000
4    Eve   78000         436000

### 3.5 Melt & Stack/Unstack (Reshaping)

In [56]:
wide = pd.DataFrame({
    'name': ['Alice','Bob'],
    'q1': [100, 80],
    'q2': [120, 90],
    'q3': [110, 95],
})

# wide → long
long = wide.melt(id_vars='name', var_name='quarter', value_name='revenue')
print(long)
print("-"*20)
# long → wide
back = long.pivot(index='name', columns='quarter', values='revenue')
back

    name quarter  revenue
0  Alice      q1      100
1    Bob      q1       80
2  Alice      q2      120
3    Bob      q2       90
4  Alice      q3      110
5    Bob      q3       95
--------------------

quarter   q1   q2   q3
name
Alice    100  120  110
Bob       80   90   95

### 3.6 Categorical Dtype & Memory Optimization

In [58]:
before = df['dept'].memory_usage(deep=True)
df['dept_cat'] = df['dept'].astype('category')
after  = df['dept_cat'].memory_usage(deep=True)
print(f'dept  object:   {before} bytes')
print("-"*20)
print(f'dept  category: {after} bytes')
print("-"*20)
print(f'Reduction: {(1 - after/before)*100:.1f}%')
print("-"*20)
print(df['dept_cat'].cat.categories.tolist())

dept  object:   429 bytes
--------------------
dept  category: 315 bytes
--------------------
Reduction: 26.6%
--------------------
['DS', 'Eng', 'PM']

### 3.7 Custom Aggregation with pipe

In [59]:
def add_senior_flag(df_):
    return df_.assign(is_senior=df_['yoe'] >= 5)

def normalize_salary(df_):
    return df_.assign(salary_norm=(df_['salary'] - df_['salary'].min()) / (df_['salary'].max() - df_['salary'].min()))

result = (
    df[['name','dept','salary','yoe']]
    .pipe(add_senior_flag)
    .pipe(normalize_salary)
    .sort_values('salary_norm', ascending=False)
)
result

    name dept  salary  yoe  is_senior  salary_norm
2  Carol  Eng   95000    7       True     1.000000
0  Alice  Eng   90000    5       True     0.705882
3   Dave   DS   88000    4      False     0.588235
1    Bob   DS   85000    3      False     0.411765
4    Eve   PM   78000    2      False     0.000000

### 3.8 explode — One Row per List Element

In [62]:
skills_df = pd.DataFrame({
    'name'  : ['Alice', 'Bob', 'Carol'],
    'skills': [['Python','SQL','ML'], ['SQL','Tableau'], ['Python','Spark','Kafka']],
})
skills_df
skills_df.explode('skills').reset_index(drop=True)

    name                  skills
0  Alice       [Python, SQL, ML]
1    Bob          [SQL, Tableau]
2  Carol  [Python, Spark, Kafka]

### 3.9 Advanced GroupBy — Named Aggregation & Filter

In [68]:
# GroupBy filter — keep only groups with > 1 member
df_filtered = df.groupby('dept').filter(lambda g: len(g) > 1)
print('Depts with >1 member:')
print(df_filtered[['name','dept']])

Depts with >1 member:
    name dept
0  Alice  Eng
1    Bob   DS
2  Carol  Eng
3   Dave   DS

In [69]:
# GroupBy apply — custom function per group
def top_earner(group):
    return group.nlargest(1, 'salary')[['name','salary']]

df.groupby('dept', group_keys=False).apply(top_earner)

    name  salary
3   Dave   88000
2  Carol   95000
4    Eve   78000

### 3.10 Performance — vectorized ops vs apply

In [70]:
import time

big = pd.DataFrame({'x': np.random.randn(500_000)})

# apply (slow)
t0 = time.perf_counter()
big['x'].apply(lambda v: v ** 2)
t_apply = time.perf_counter() - t0
print("-"*20)
# vectorized (fast)
t0 = time.perf_counter()
big['x'] ** 2
t_vec = time.perf_counter() - t0

print(f'apply     : {t_apply*1000:.1f} ms')
print("-"*20)
print(f'vectorized: {t_vec*1000:.1f} ms')
print("-"*20)
print(f'Speedup   : {t_apply/t_vec:.0f}x')

--------------------
apply     : 162.0 ms
--------------------
vectorized: 1.6 ms
--------------------
Speedup   : 100x

### 3.11 Read / Write CSV & JSON

In [ ]:
# Write
df[['name','dept','salary','yoe']].to_csv('/tmp/employees.csv', index=False)
df[['name','dept','salary','yoe']].to_json('/tmp/employees.json', orient='records', indent=2)

# Read back
df_csv  = pd.read_csv('/tmp/employees.csv')
df_json = pd.read_json('/tmp/employees.json')

print(df_csv.head())
print(df_json.head())

### 3.12 Method Chaining (Fluent Style)

In [ ]:
result = (
    df
    .query("dept != 'PM'")
    .assign(bonus=lambda d: d['salary'] * 0.10)
    .groupby('dept')
    .agg(total_bonus=('bonus', 'sum'), headcount=('name', 'count'))
    .sort_values('total_bonus', ascending=False)
    .reset_index()
)
result

---
## ✅ Quick Reference Cheatsheet

| Operation | Code |
|-----------|------|
| Select column | `df['col']` |
| Filter rows | `df[df['col'] > val]` / `df.query(...)` |
| Label-based select | `df.loc[rows, cols]` |
| Position-based select | `df.iloc[r, c]` |
| Group + aggregate | `df.groupby('col').agg(...)` |
| Merge | `df.merge(df2, on='key', how='left')` |
| Stack vertically | `pd.concat([df1, df2])` |
| Pivot | `df.pivot_table(values, index, columns, aggfunc)` |
| Reshape wide→long | `df.melt(id_vars, var_name, value_name)` |
| Fill NaN | `df.fillna(val)` / `ffill()` / `bfill()` |
| Drop NaN | `df.dropna(subset=['col'])` |
| Rank in group | `df.groupby('g')['col'].rank()` |
| Rolling window | `s.rolling(n).mean()` |
| Resample time | `s.resample('QE').sum()` |
| Chain methods | `df.pipe(fn1).pipe(fn2)` |